### ISSUE TITLE
jasur0707

### ISSUE THREAD

**Issue by jasur0707** [shubhankar5/Mitron-A-chatting-app-in-django#1]
hello brother how are you brother I had a question, I used the program from this site: https://github.com/shubhankar5/Mitron-A-chatting-app-in-django, I have this problem:    django.db.utils.ProgrammingError: ОШИБКА:  отношение "messaging_messages" не существует
LINE 1: SELECT (1) AS "a" FROM "messaging_messages" WHERE ("messagin...     

(•	lib\site-packages\django\contrib\auth\decorators.py in _wrapped_view
21.	                return view_func(request, *args, **kwargs)
 …
•	▶ Local vars
•	C:\Users\Jasur\Desktop\AAAA\chat_app\users\views.py in home
383.			if Messages.objects.filter(	Q(sender=request.user)|
 

376.	return redirect('init')
377.	
378.	
379.	@require_http_methods(["GET", "POST"])
380.	@login_required
381.	def home(request):
382.		if request.user.profile.first_name:
383.			if Messages.objects.filter(	Q(sender=request.user)|
 …
384.										Q(receiver=request.user)
385.								).exists():
386.				has_messages = True
387.			else:
388.				has_messages = False
389.			return render(request,'users/home.html', { 'has_messages' : has_messages})
)

**Comment by jasur0707** [comment]
jasurbek5uzbest@gmail.com  my gmail account  reply me please

**Comment by shubhankar5** [comment]
Hey bro, the error you're seeing basically means that a table hasn't been created or Django is unable to find it in the database. So, the solution I would recommend is to delete all the tables and recreate them. For this you have to do the following steps:

- Delete db.sqllite3 file, which will delete all database entries.
- Delete all migration files inside both **messaging** and **users** app in the project
- Run `python manage.py makemigrations` and then `python manage.py migrate`
